{
  "openapi": "3.0.0",
  "info": {
      "title": "Atlas",
      "description": "Essa é uma documentação sobre a Atlas API.",
      "version": "1.0.0"
  },
  "tags": [
      {
        "name": "users",
        "description": "Gerencimanto de usuários"
      }
  ],
  "paths": {
      "/users": {
          "post": {
              "tags": [
                  "users"
              ],
              "summary": "Cria um novo usuário",
              "operationId": "addUser",
              "consumes": "application/json",
              "produces": "application/json",
              "requestBody": {
                  "content": {
                      "application/json": {
                          "schema": {
                              "type": "object",
                              "properties": {
                                  "name": {
                                      "type": "string"
                                  },
                                  "email": {
                                      "type": "string"
                                  }
                              },
                              "example": {
                                  "name": "User1",
                                  "email": "user1@example.com.br"
                              }
                          }
                      }
                  },
                  "required": true
              },
              "responses": {
                  "201": {
                      "description": "Operação realizada com sucesso.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "items": {
                                      "$ref": "#/components/schemas/User"
                                  }
                              },
                              "examples": {
                                  "UserExample": {
                                      "$ref": "#/components/examples/UserExample"
                                  }
                              }
                          }
                      }
                  },
                  "400": {
                      "description": "Usuário já existe.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "properties": {
                                      "error": {
                                          "example": "User already exists"
                                      }
                                  }

                              }
                          }
                      }
                  }
              }
          },
          "get": {
              "tags": [
                  "users"
              ],
              "summary": "Retorna todos os usuários",
              "description": "Somente usuário `admin` pode acessar.",
              "parameters": [
                  {
                      "name": "user_id",
                      "in": "header",
                      "required": true,
                      "schema": {
                          "type": "string",
                          "format": "uuid"
                      }
                  }
              ],
              "responses": {
                  "200": {
                      "description": "Operação realizada com sucesso.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "array",
                                  "items": {
                                      "$ref": "#/components/schemas/User"
                                  }
                              },
                              "examples": {
                                  "UsersExample": {
                                      "$ref": "#/components/examples/UsersExample"
                                  }
                              }
                          }
                      }
                  },
                  "400": {
                      "description": "Usuário sem permissão ou Usuário não encontrado.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "properties": {
                                      "error": {
                                          "example": "User without permission"
                                      }
                                  }

                              }
                          }
                      }
                  }
              }
          }
      },
      "/users/{user_id}": {
          "get": {
              "tags": [
                  "users"
              ],
              "summary": "Retorna um usuário específico.",
              "parameters": [
                  {
                      "name": "user_id",
                      "in": "params",
                      "required": true,
                      "schema": {
                          "type": "string",
                          "format": "uuid"
                      }
                  }
              ],
              "responses": {
                  "200": {
                      "description": "Operação realizada com sucesso.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "items": {
                                      "$ref": "#/components/schemas/User"
                                  }
                              },
                              "examples": {
                                  "UserExample": {
                                      "$ref": "#/components/examples/UserExample"
                                  }
                              }
                          }
                      }
                  },
                  "400": {
                      "description": "Usuário não existe.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "properties": {
                                      "error": {
                                          "example": "User not exists"
                                      }
                                  }

                              }
                          }
                      }
                  }
              }
          }
      },
      "/users/{user_id}/admin": {
          "patch": {
              "tags": [
                  "users"
              ],
              "summary": "Torna um usuário específico em admin.",
              "parameters": [
                  {
                      "name": "user_id",
                      "in": "params",
                      "required": true,
                      "schema": {
                          "type": "string",
                          "format": "uuid"
                      }
                  }
              ],
              "responses": {
                  "200": {
                      "description": "Operação realizada com sucesso.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "items": {
                                      "$ref": "#/components/schemas/User"
                                  }
                              },
                              "examples": {
                                  "UserExample": {
                                      "$ref": "#/components/examples/UserExampleAdmin"
                                  }
                              }
                          }
                      }
                  },
                  "404": {
                      "description": "Usuário não existe.",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "object",
                                  "properties": {
                                      "error": {
                                          "example": "User not exists"
                                      }
                                  }

                              }
                          }
                      }
                  }
              }
          }
      }
  },
  "components": {
      "schemas": {
        "User": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid"
            },
            "admin": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            }
          }
        }
      },
      "examples": {
        "UserExample": {
          "value": {
            "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
            "admin": false,
            "name": "User1",
            "email": "user1@example.com.br",
            "created_at": "2021-03-10T22:10:32.992Z",
            "updated_at": "2021-03-10T22:10:32.992Z"
          }
        },
        "UserExampleAdmin": {
          "value": {
            "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
            "admin": true,
            "name": "User1",
            "email": "user1@example.com.br",
            "created_at": "2021-03-10T22:10:32.992Z",
            "updated_at": "2021-03-10T22:10:32.992Z"
          }
        },
        "UsersExample": {
          "value": [
            {
              "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
              "admin": false,
              "name": "User1",
              "email": "user1@example.com.br",
              "created_at": "2021-03-10T22:10:32.992Z",
              "updated_at": "2021-03-10T22:10:32.992Z"
            },
            {
              "id": "2e930901-cb97-403a-a7ac-c48d859ba188",
              "admin": true,
              "name": "User2",
              "email": "user2@example.com.br",
              "created_at": "2021-03-22T15:10:32.992Z",
              "updated_at": "2021-03-22T15:10:32.992Z"
            }
          ]    
        }
      }
    }
}